# Generated by Django 3.0.2 on 2020-07-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolClass', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Class and SubClass of the student', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolClass.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.CharField(help_text='Number of registration. The first numbers are the current year', max_length=12, unique=True, verbose_name='Registration of the student in school'),
        ),
    ]
